import type { Item, Category, Supplier } from './types'

export const DEFAULT_ITEMS: Item[] = [
  {id:'p1',name_th:'ขาหน้าหมูเผา',name_mm:'ဝက်ခြေမီးကင်',category:'pork',supplier:'เบทาโกร/เฮียติ่ง',unit_th:'กก.',unit_mm:'ကီလို',minStock:10,currentStock:null,image:null},
  {id:'p2',name_th:'เนื้อขาหมู เลาะกระดูก',name_mm:'ဝက်ခြေသား',category:'pork',supplier:'เบทาโกร',unit_th:'กก.',unit_mm:'ကီလို',minStock:5,currentStock:null,image:null},
  {id:'p3',name_th:'คากิ',name_mm:'ကာကိ',category:'pork',supplier:'เบทาโกร',unit_th:'กก.',unit_mm:'ကီလို',minStock:3,currentStock:null,image:null},
  {id:'p4',name_th:'ซี่โครงหมูตัดเส้น',name_mm:'ဝက်ကုက်',category:'pork',supplier:'เฮียติ่ง',unit_th:'กก.',unit_mm:'ကီလို',minStock:5,currentStock:null,image:null},
  {id:'p5',name_th:'กระดูกซุปหมู เล้ง',name_mm:'ဝက်ရိုးဟင်းရည်',category:'pork',supplier:'เฮียติ่ง',unit_th:'กก.',unit_mm:'ကီလို',minStock:5,currentStock:null,image:null},
  {id:'p6',name_th:'กระดูกข้อขา',name_mm:'ဝက်ဒူးရိုး',category:'pork',supplier:'เฮียติ่ง',unit_th:'กก.',unit_mm:'ကီလို',minStock:5,currentStock:null,image:null},
  {id:'p7',name_th:'ไส้ใหญ่ดึงมัน',name_mm:'ဝက်အူကြီး',category:'pork',supplier:'มหาชัย',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'p8',name_th:'มันหมูหั่นเต๋า',name_mm:'ဝက်ဆီတုံး',category:'pork',supplier:'มหาชัย',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'p9',name_th:'หูหมู แช่แข็ง',name_mm:'ဝက်နား',category:'pork',supplier:'มหาชัย',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'p10',name_th:'กุนเชียง',name_mm:'ကုန်ချင်',category:'pork',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:1,currentStock:null,image:null},
  {id:'c1',name_th:'สะโพกไก่ติดกระดูก',name_mm:'ကြက်ပေါင်ထိပ်',category:'chicken',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:5,currentStock:null,image:null},
  {id:'r1',name_th:'ไข่เป็ด ARO',name_mm:'ဘဲဥ',category:'ready',supplier:'Makro',unit_th:'ฟอง',unit_mm:'လုံး',minStock:30,currentStock:null,image:null},
  {id:'r2',name_th:'ไข่ไก่',name_mm:'ကြက်ဥ',category:'ready',supplier:'Makro',unit_th:'ฟอง',unit_mm:'လုံး',minStock:150,currentStock:null,image:null},
  {id:'r3',name_th:'ข้าวหอมมะลิ เบญจรง',name_mm:'ထမင်း',category:'ready',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:20,currentStock:null,image:null},
  {id:'r4',name_th:'บะหมี่ไข่วิรัตน์',name_mm:'မုန့်ဟင်းခါးမျဉ်း',category:'ready',supplier:'Makro',unit_th:'ก้อน',unit_mm:'ခဲ',minStock:50,currentStock:null,image:null},
  {id:'r5',name_th:'เต้าหู้ทอดหนา ซากุระ',name_mm:'တိုဖူး',category:'ready',supplier:'Makro',unit_th:'ก้อน',unit_mm:'ခဲ',minStock:30,currentStock:null,image:null},
  {id:'s1',name_th:'Yamamori Shoyu ซอสถั่วเหลือง',name_mm:'ပဲငံပြာရည်',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:3,currentStock:null,image:null},
  {id:'s2',name_th:'น้ำตาลทรายขาว มิตรผล',name_mm:'သကြားဖြူ',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:5,currentStock:null,image:null},
  {id:'s3',name_th:'พริกไทยดำ aro',name_mm:'ငရုတ်ကောင်းမှောင်',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:1,currentStock:null,image:null},
  {id:'s4',name_th:'เกลือปรุงทิพย์',name_mm:'ဆား',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'s5',name_th:'ภูเขาทอง ซอสปรุง',name_mm:'ဟင်းချက်ဆော့စ်',category:'seasoning',supplier:'Makro/มหาชัย',unit_th:'ขวด',unit_mm:'ဘူး',minStock:3,currentStock:null,image:null},
  {id:'s6',name_th:'เด็กสมบูรณ์ ซีอิ๊วขาว',name_mm:'ပဲငံပြာရည်ဖြူ',category:'seasoning',supplier:'Makro/มหาชัย',unit_th:'ขวด',unit_mm:'ဘူး',minStock:3,currentStock:null,image:null},
  {id:'s7',name_th:'น้ำตาลมะพร้าว',name_mm:'အုန်းသကြား',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'s8',name_th:'คิวพี น้ำส้มสายชู',name_mm:'ချဉ်',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s9',name_th:'น้ำตาลทรายแดง มิตรผล',name_mm:'သကြားညိုမ',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'s10',name_th:'รสดี ซุปก้อนหมูกระดูก',name_mm:'ဝက်ရိုးဟင်းရည်',category:'seasoning',supplier:'Makro',unit_th:'กล่อง',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s11',name_th:'ผงชูรส อายิโนะโมะโต๊ะ',name_mm:'အာဂျီ',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.5,currentStock:null,image:null},
  {id:'s12',name_th:'ลีกุมกี่ ซอสหอยนางรม',name_mm:'ကမာငံပြာ',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s13',name_th:'ง่วนเชียง ซีอิ๊วหวาน',name_mm:'ချိုသောပဲငံပြာ',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s14',name_th:'น้ำตาลกรวด วังขนาย',name_mm:'ကျောက်သကြား',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:1,currentStock:null,image:null},
  {id:'s15',name_th:'พริกไทยขาวป่น',name_mm:'ငရုတ်ကောင်းဖြူ',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s16',name_th:'น้ำมันปาล์ม ปี๊บ',name_mm:'ပန်းသီးဆီ',category:'seasoning',supplier:'Makro',unit_th:'ปี๊บ',unit_mm:'ပိဉ်',minStock:1,currentStock:null,image:null},
  {id:'s17',name_th:'น้ำมันงา ตรามังกรคู่',name_mm:'နှမ်းဆီ',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s18',name_th:'น้ำมะนาวแช่แข็ง',name_mm:'သံပရာနှစ်ရည်',category:'seasoning',supplier:'มหาชัย',unit_th:'ถุง',unit_mm:'အိတ်',minStock:3,currentStock:null,image:null},
  {id:'s19',name_th:'ซีอิ๊วหวาน ตราธงคู่ จี้แช',name_mm:'ချိုသောပဲငံပြာ2',category:'seasoning',supplier:'Shopee',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s20',name_th:'น้ำซุปหมูสูตรเข้มข้น',name_mm:'ဝက်ဟင်းရည်သုပ်',category:'seasoning',supplier:'เบทาโกร',unit_th:'ถุง',unit_mm:'အိတ်',minStock:5,currentStock:null,image:null},
  {id:'s21',name_th:'น้ำมันพริก เหล่ากานมา',name_mm:'ငရုတ်ဆီ',category:'seasoning',supplier:'Makro/Go Wholesale',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s22',name_th:'เม็ดหม่าล่า ฮวาเจียว',name_mm:'မာလာကဆုပ်',category:'seasoning',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.5,currentStock:null,image:null},
  {id:'s23',name_th:'เอโร่ สาเกปรุงอาหาร',name_mm:'ဆာကေ',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s24',name_th:'ฮอนดาชิ ผงปรุง',name_mm:'ဟွန်ဒါချိ',category:'seasoning',supplier:'Makro',unit_th:'ถุง',unit_mm:'အိတ်',minStock:2,currentStock:null,image:null},
  {id:'v1',name_th:'เม็ดผักชี',name_mm:'နွားသလဲစေ့',category:'vegetable',supplier:'Makro/มหาชัย',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'v2',name_th:'ข่าอบแห้ง',name_mm:'ကျည်ပေါင်ခြောက်',category:'vegetable',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'v3',name_th:'อบเชยแท่ง Cinnamon',name_mm:'သပြေကြောင်း',category:'vegetable',supplier:'Makro/มหาชัย',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'v4',name_th:'โป้ยกั๊ก',name_mm:'ကြယ်ပွင့်',category:'vegetable',supplier:'Makro/มหาชัย',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'v5',name_th:'ข่าอ่อน สด',name_mm:'ကျည်ပေါင်',category:'vegetable',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.5,currentStock:null,image:null},
  {id:'v6',name_th:'ขิงแก่ สด',name_mm:'နနတ်',category:'vegetable',supplier:'Makro/ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.5,currentStock:null,image:null},
  {id:'v7',name_th:'พริกเหลือง',name_mm:'ငရုတ်ဝါ',category:'vegetable',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'v8',name_th:'รากผักชี',name_mm:'နွားသလဲမြစ်',category:'vegetable',supplier:'Makro/ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'v9',name_th:'กระเทียมไทย แกะกลีบ',name_mm:'ကြက်သွန်ဖြူ',category:'vegetable',supplier:'Makro/ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:1,currentStock:null,image:null},
  {id:'v10',name_th:'ผักกาดดองเปรี้ยว',name_mm:'မုန်ညင်းချဉ်',category:'vegetable',supplier:'Makro/ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:2,currentStock:null,image:null},
  {id:'v11',name_th:'กระเทียมจีน',name_mm:'တရုတ်ကြက်သွန်ဖြူ',category:'vegetable',supplier:'Makro/ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:1,currentStock:null,image:null},
  {id:'v12',name_th:'กระเทียมดอง แม่จินต์',name_mm:'ကြက်သွန်ဖြူချဉ်',category:'vegetable',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.5,currentStock:null,image:null},
  {id:'v13',name_th:'เห็ดหอม',name_mm:'မှိုရနံ့',category:'vegetable',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'v14',name_th:'พริกขี้หนู',name_mm:'ငရုတ်သီးသေး',category:'vegetable',supplier:'ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'v15',name_th:'มะระจีน',name_mm:'ဆလာကျားသီး',category:'vegetable',supplier:'ขอนแก่นผักสด',unit_th:'กก.',unit_mm:'ကီလို',minStock:1,currentStock:null,image:null},
  {id:'v16',name_th:'งาขาว',name_mm:'နှမ်းဖြူ',category:'vegetable',supplier:'Makro',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'h1',name_th:'เม็ดเฉาก๊วย',name_mm:'ကန်ကျောဆေးစေ့',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.3,currentStock:null,image:null},
  {id:'h2',name_th:'กำเช่า ชะเอมเทศ',name_mm:'ချိုဆေး',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'h3',name_th:'ปักคี้',name_mm:'ပကီ',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'h4',name_th:'ฮวยซัว',name_mm:'ဖွားဆွာ',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'h5',name_th:'เก๋ากี้',name_mm:'ကော်ကီး',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'h6',name_th:'ตังกุย',name_mm:'တန်ကွေး',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'h7',name_th:'ตังเซียม',name_mm:'တန်ဆယ်',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'h8',name_th:'พุทราจีน',name_mm:'တရုတ်ဆီးသီး',category:'herb',supplier:'Shopee',unit_th:'กก.',unit_mm:'ကီလို',minStock:0.2,currentStock:null,image:null},
  {id:'s26',name_th:'ซอสเหยาะ แม็กกี้',name_mm:'မာကီဆော့စ်',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s27',name_th:'คนอร์ไก่ ซุปก้อน',name_mm:'ကြောင်ဟင်းရည်ပြုတ်',category:'seasoning',supplier:'Makro',unit_th:'กล่อง',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s28',name_th:'ซวงเจียแดง',name_mm:'ဆွမ်ကျာနီ',category:'seasoning',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s29',name_th:'ชาจีน',name_mm:'တရုတ်လက်ဖက်',category:'seasoning',supplier:'Makro',unit_th:'กล่อง',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'s30',name_th:'น้ำแร่',name_mm:'သဘာဝရေ',category:'seasoning',supplier:'Makro',unit_th:'แพ็ก',unit_mm:'ပက်',minStock:5,currentStock:null,image:null},
  {id:'pk1',name_th:'ถุง 9×8',name_mm:'အိတ် 9×8',category:'packaging',supplier:'มหาชัย',unit_th:'ม้วน',unit_mm:'တိုင်',minStock:5,currentStock:null,image:null},
  {id:'pk2',name_th:'ถุงน้ำราด 5×8',name_mm:'ဟင်းချောင်းအိတ် 5×8',category:'packaging',supplier:'มหาชัย',unit_th:'ม้วน',unit_mm:'တိုင်',minStock:5,currentStock:null,image:null},
  {id:'pk3',name_th:'ถุงพริกกระเทียม 3×5',name_mm:'ငရုတ်ကြက်သွန်အိတ် 3×5',category:'packaging',supplier:'มหาชัย',unit_th:'ม้วน',unit_mm:'တိုင်',minStock:3,currentStock:null,image:null},
  {id:'pk4',name_th:'กล่องใสขาวสีดำ',name_mm:'အမဲဘူး',category:'packaging',supplier:'มหาชัย',unit_th:'ใบ',unit_mm:'ဘူး',minStock:200,currentStock:null,image:null},
  {id:'pk5',name_th:'กล่องใสขาวสีขาว',name_mm:'အဖြူဘူး',category:'packaging',supplier:'มหาชัย',unit_th:'ใบ',unit_mm:'ဘူး',minStock:200,currentStock:null,image:null},
  {id:'pk6',name_th:'ถ้วยน้ำจิ้ม',name_mm:'ငံပြာရည်ခွက်',category:'packaging',supplier:'มหาชัย',unit_th:'ใบ',unit_mm:'ခွက်',minStock:200,currentStock:null,image:null},
  {id:'pk7',name_th:'ทิชชูวางโต๊ะ',name_mm:'စားပွဲတင်တစ်ရႈ',category:'packaging',supplier:'มหาชัย',unit_th:'ห่อ',unit_mm:'ထုပ်',minStock:10,currentStock:null,image:null},
  {id:'pk8',name_th:'หลอด',name_mm:'စုပ်ပြွန်',category:'packaging',supplier:'มหาชัย',unit_th:'แพ็ก',unit_mm:'ပက်',minStock:5,currentStock:null,image:null},
  {id:'pk9',name_th:'ยางรัด',name_mm:'ကျည်ကြိုး',category:'packaging',supplier:'มหาชัย',unit_th:'ถุง',unit_mm:'အိတ်',minStock:2,currentStock:null,image:null},
  {id:'pk10',name_th:'ถุงมือสีดำ',name_mm:'လက်အိတ်နက်',category:'packaging',supplier:'มหาชัย',unit_th:'กล่อง',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'pk11',name_th:'ถุงขยะ',name_mm:'အမှိုက်အိတ်',category:'packaging',supplier:'มหาชัย',unit_th:'ม้วน',unit_mm:'တိုင်',minStock:3,currentStock:null,image:null},
  {id:'pk12',name_th:'แผ่นแรป',name_mm:'ကလပ်ရပ်',category:'packaging',supplier:'มหาชัย',unit_th:'ม้วน',unit_mm:'တိုင်',minStock:2,currentStock:null,image:null},
  {id:'pk13',name_th:'เทปใส',name_mm:'ကြည်တိတ်',category:'packaging',supplier:'มหาชัย',unit_th:'ม้วน',unit_mm:'တိုင်',minStock:3,currentStock:null,image:null},
  {id:'pk14',name_th:'ลูกแม็ก',name_mm:'မင်ကျည်',category:'packaging',supplier:'มหาชัย',unit_th:'กล่อง',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'pk15',name_th:'น้ำยาล้างจาน',name_mm:'ပန်းကန်ဆေးရည်',category:'packaging',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:3,currentStock:null,image:null},
  {id:'pk16',name_th:'น้ำยาถูพื้น',name_mm:'ကြမ်းပြင်ဆေးရည်',category:'packaging',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
  {id:'pk17',name_th:'น้ำยาเช็ดโต๊ะ',name_mm:'စားပွဲဆေးရည်',category:'packaging',supplier:'Makro',unit_th:'ขวด',unit_mm:'ဘူး',minStock:2,currentStock:null,image:null},
]

export const DEFAULT_CATEGORIES: Category[] = [
  {id:'pork',      name_th:'เนื้อหมู',             emoji:'🥩', sort_order:0},
  {id:'chicken',   name_th:'เนื้อไก่',             emoji:'🐔', sort_order:1},
  {id:'ready',     name_th:'ของสำเร็จรูป',         emoji:'🥚', sort_order:2},
  {id:'seasoning', name_th:'เครื่องปรุง',          emoji:'🧂', sort_order:3},
  {id:'vegetable', name_th:'ผัก & สมุนไพร',       emoji:'🥬', sort_order:4},
  {id:'herb',      name_th:'สมุนไพรจีน',           emoji:'🌿', sort_order:5},
  {id:'packaging', name_th:'บรรจุภัณฑ์ & วัสดุ', emoji:'📦', sort_order:6},
]

export const DEFAULT_SUPPLIERS: Supplier[] = [
  {id:'ds1', name:'เบทาโกร'},
  {id:'ds2', name:'เฮียติ่ง'},
  {id:'ds3', name:'มหาชัย'},
  {id:'ds4', name:'Makro'},
  {id:'ds5', name:'ขอนแก่นผักสด'},
  {id:'ds6', name:'Shopee'},
  {id:'ds7', name:'Go Wholesale'},
]
