import type { Item, Category, Supplier } from './types'

export const DEFAULT_ITEMS: Item[] = [
  // หมู / ၼိူဝ်ႉမူ
  {id:'p1', name_th:'ขาหน้าหมูเผา',         name_mm:'ၶႃႈၼႃႈမူၾႆးၶႅတ်ႈ',    category:'pork', supplier:'เบทาโกร/เฮียติ่ง', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:10, currentStock:null, image:null},
  {id:'p2', name_th:'เนื้อขาหมู เลาะกระดูก', name_mm:'ၼိူဝ်ႉၶႃႈမူ',          category:'pork', supplier:'เบทาโกร',          unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:5,  currentStock:null, image:null},
  {id:'p3', name_th:'คากิ',                  name_mm:'ၶႃၵျိ',               category:'pork', supplier:'เบทาโกร',          unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:3,  currentStock:null, image:null},
  {id:'p4', name_th:'ซี่โครงหมูตัดเส้น',     name_mm:'ၶွင်းၶၢမ်ႇမူ',         category:'pork', supplier:'เฮียติ่ง',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:5,  currentStock:null, image:null},
  {id:'p5', name_th:'กระดูกซุปหมู เล้ง',     name_mm:'ၸိူင်ႇမူႁူမ်ႈ',        category:'pork', supplier:'เฮียติ่ง',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:5,  currentStock:null, image:null},
  {id:'p6', name_th:'กระดูกข้อขา',           name_mm:'ၸိူင်ႇၶႃႈ',           category:'pork', supplier:'เฮียติ่ง',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:5,  currentStock:null, image:null},
  {id:'p7', name_th:'ไส้ใหญ่ดึงมัน',         name_mm:'ၵႂၢင်ႈမူ',            category:'pork', supplier:'มหาชัย',           unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,  currentStock:null, image:null},
  {id:'p8', name_th:'มันหมูหั่นเต๋า',         name_mm:'မၼ်ႈမူ',              category:'pork', supplier:'มหาชัย',           unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,  currentStock:null, image:null},
  {id:'p9', name_th:'หูหมู แช่แข็ง',          name_mm:'ၼႅတ်ႈမူ',             category:'pork', supplier:'มหาชัย',           unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,  currentStock:null, image:null},
  {id:'p10',name_th:'กุนเชียง',              name_mm:'ၵုၼ်းၶျမ်ႈ',          category:'pork', supplier:'Makro',            unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:1,  currentStock:null, image:null},
  // ไก่ / ၼိူဝ်ႉၵႆႇ
  {id:'c1', name_th:'สะโพกไก่ติดกระดูก',     name_mm:'တင်ႉၵႆႇၵမ်ႇၸိူင်ႇ',   category:'chicken', supplier:'Makro',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:5,  currentStock:null, image:null},
  // ของสำเร็จรูป
  {id:'r1', name_th:'ไข่เป็ด ARO',           name_mm:'ၵိူဝ်ႇပဵတ်း',         category:'ready', supplier:'Makro',           unit_th:'ฟอง', unit_mm:'ၵိူဝ်ႇ',    minStock:30, currentStock:null, image:null},
  {id:'r2', name_th:'ไข่ไก่',               name_mm:'ၵိူဝ်ႇၵႆႇ',           category:'ready', supplier:'Makro',           unit_th:'ฟอง', unit_mm:'ၵိူဝ်ႇ',    minStock:150,currentStock:null, image:null},
  {id:'r3', name_th:'ข้าวหอมมะลิ เบญจรง',   name_mm:'ၶဝ်ႈႁုၼ်ႈ',           category:'ready', supplier:'Makro',           unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:20, currentStock:null, image:null},
  {id:'r4', name_th:'บะหมี่ไข่วิรัตน์',       name_mm:'မုၼ်ႉၵိူဝ်ႇ',          category:'ready', supplier:'Makro',           unit_th:'ก้อน',unit_mm:'ၵိုၵ်း',   minStock:50, currentStock:null, image:null},
  {id:'r5', name_th:'เต้าหู้ทอดหนา ซากุระ',  name_mm:'တူဝ်ႉႁူ',             category:'ready', supplier:'Makro',           unit_th:'ก้อน',unit_mm:'ၵိုၵ်း',   minStock:30, currentStock:null, image:null},
  // เครื่องปรุง
  {id:'s1', name_th:'Yamamori Shoyu ซอสถั่วเหลือง', name_mm:'ၼမ်ႉမၢၵ်ႇထူဝ်ႇ',    category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:3,  currentStock:null, image:null},
  {id:'s2', name_th:'น้ำตาลทรายขาว มิตรผล',  name_mm:'ၼမ်ႉႁၢၼ်ႈၶၢဝ်',       category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:5,  currentStock:null, image:null},
  {id:'s3', name_th:'พริกไทยดำ aro',         name_mm:'ၽိၵ်ႇမိူင်းမိူင်း',    category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:1,  currentStock:null, image:null},
  {id:'s4', name_th:'เกลือปรุงทิพย์',         name_mm:'ၵဵင်ႇ',               category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,  currentStock:null, image:null},
  {id:'s5', name_th:'ภูเขาทอง ซอสปรุง',      name_mm:'ၼမ်ႉတမ်ၵိၼ်',         category:'seasoning', supplier:'Makro/มหาชัย', unit_th:'ขวด', unit_mm:'ၵမ်း', minStock:3,  currentStock:null, image:null},
  {id:'s6', name_th:'เด็กสมบูรณ์ ซีอิ๊วขาว', name_mm:'ၼမ်ႉမၢၵ်ႇထူဝ်ႇၶၢဝ်',  category:'seasoning', supplier:'Makro/มหาชัย', unit_th:'ขวด', unit_mm:'ၵမ်း', minStock:3,  currentStock:null, image:null},
  {id:'s7', name_th:'น้ำตาลมะพร้าว',         name_mm:'ၼမ်ႉႁၢၼ်ႈမၢၵ်ႇႁေႃ',   category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,  currentStock:null, image:null},
  {id:'s8', name_th:'คิวพี น้ำส้มสายชู',     name_mm:'ၼမ်ႉမူင်ႈ',            category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s9', name_th:'น้ำตาลทรายแดง มิตรผล',  name_mm:'ၼမ်ႉႁၢၼ်ႈလႅင်',       category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,  currentStock:null, image:null},
  {id:'s10',name_th:'รสดี ซุปก้อนหมูกระดูก', name_mm:'ၵိုၵ်းႁူမ်ႈမူ',        category:'seasoning', supplier:'Makro',    unit_th:'กล่อง',unit_mm:'ၵႃႉ',    minStock:2,  currentStock:null, image:null},
  {id:'s11',name_th:'ผงชูรส อายิโนะโมะโต๊ะ', name_mm:'ၽွင်ႈပႂ်ႉၵိၼ်',        category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.5,currentStock:null, image:null},
  {id:'s12',name_th:'ลีกุมกี่ ซอสหอยนางรม',  name_mm:'ၼမ်ႉမၢၵ်ႇႁမ်ႈ',        category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s13',name_th:'ง่วนเชียง ซีอิ๊วหวาน',  name_mm:'ၼမ်ႉမၢၵ်ႇထူဝ်ႇဝၢၼ်',  category:'seasoning', supplier:'Makro/มหาชัย', unit_th:'ขวด', unit_mm:'ၵမ်း', minStock:2,  currentStock:null, image:null},
  {id:'s14',name_th:'น้ำตาลกรวด วังขนาย',    name_mm:'ၼမ်ႉႁၢၼ်ႈၵႅၼ်ႇ',      category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:1,  currentStock:null, image:null},
  {id:'s15',name_th:'พริกไทยขาวป่น',         name_mm:'ၽိၵ်ႇမိူင်းၶၢဝ်',      category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s16',name_th:'น้ำมันปาล์ม ปี๊บ',      name_mm:'ၼမ်ႉမၼ်ႈမၢၵ်ႇၵမ်ႇ',   category:'seasoning', supplier:'Makro',    unit_th:'ปี๊บ',unit_mm:'မဵဝ်ႈ',    minStock:1,  currentStock:null, image:null},
  {id:'s17',name_th:'น้ำมันงา ตรามังกรคู่',   name_mm:'ၼမ်ႉမၼ်ႈမေႃ',         category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s18',name_th:'น้ำมะนาวแช่แข็ง',       name_mm:'ၼမ်ႉမၢၵ်ႇမၢဝ်ႇ',       category:'seasoning', supplier:'มหาชัย',   unit_th:'ถุง', unit_mm:'ထူင်',     minStock:3,  currentStock:null, image:null},
  {id:'s19',name_th:'ซีอิ๊วหวาน ตราธงคู่ จี้แช', name_mm:'ၼမ်ႉမၢၵ်ႇထူဝ်ႇဝၢၼ် 2', category:'seasoning', supplier:'Shopee', unit_th:'ขวด', unit_mm:'ၵမ်း',  minStock:2,  currentStock:null, image:null},
  {id:'s20',name_th:'น้ำซุปหมูสูตรเข้มข้น',   name_mm:'ၼမ်ႉႁူမ်ႈမူ',          category:'seasoning', supplier:'เบทาโกร', unit_th:'ถุง', unit_mm:'ထူင်',     minStock:5,  currentStock:null, image:null},
  {id:'s21',name_th:'น้ำมันพริก เหล่ากานมา',  name_mm:'ၼမ်ႉမၼ်ႈမၢၵ်ႇၽိၵ်ႇ',  category:'seasoning', supplier:'Makro/Go Wholesale', unit_th:'ขวด', unit_mm:'ၵမ်း', minStock:2, currentStock:null, image:null},
  {id:'s22',name_th:'เม็ดหม่าล่า ฮวาเจียว',  name_mm:'မၢၵ်ႇမႃႇလႃႇ',          category:'seasoning', supplier:'Makro',    unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.5,currentStock:null, image:null},
  {id:'s23',name_th:'เอโร่ สาเกปรุงอาหาร',   name_mm:'ၼမ်ႉဢဵၼ်ၵိၼ်ၶဝ်ႈ',    category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s24',name_th:'ฮอนดาชิ ผงปรุง',        name_mm:'ႁူဝ်ၼ်တႃႇၶျိ',        category:'seasoning', supplier:'Makro',    unit_th:'ถุง', unit_mm:'ထူင်',     minStock:2,  currentStock:null, image:null},
  // ผัก & สมุนไพร
  {id:'v1', name_th:'เม็ดผักชี',             name_mm:'မၢၵ်ႇပၢၵ်ႇသီ',         category:'vegetable', supplier:'Makro/มหาชัย',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'v2', name_th:'ข่าอบแห้ง',             name_mm:'ၶႃႁ်ႅ',               category:'vegetable', supplier:'Makro',                unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'v3', name_th:'อบเชยแท่ง Cinnamon',    name_mm:'သပ်ႉပၼ်ႈ',            category:'vegetable', supplier:'Makro/มหาชัย',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'v4', name_th:'โป้ยกั๊ก',              name_mm:'ၽႃႈၽႃႈ',              category:'vegetable', supplier:'Makro/มหาชัย',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'v5', name_th:'ข่าอ่อน สด',            name_mm:'ၶႃၼုမ်ႇ',             category:'vegetable', supplier:'Makro',                unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.5, currentStock:null, image:null},
  {id:'v6', name_th:'ขิงแก่ สด',             name_mm:'ၶိင်း',               category:'vegetable', supplier:'Makro/ขอนแก่นผักสด',   unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.5, currentStock:null, image:null},
  {id:'v7', name_th:'พริกเหลือง',             name_mm:'မၢၵ်ႇၽိၵ်ႇလိူင်',     category:'vegetable', supplier:'Makro',                unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'v8', name_th:'รากผักชี',              name_mm:'ႁၢၵ်ႈပၢၵ်ႇသီ',        category:'vegetable', supplier:'Makro/ขอนแก่นผักสด',   unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'v9', name_th:'กระเทียมไทย แกะกลีบ',   name_mm:'ၵႃႇတပ်ႉထႆး',          category:'vegetable', supplier:'Makro/ขอนแก่นผักสด',   unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:1,   currentStock:null, image:null},
  {id:'v10',name_th:'ผักกาดดองเปรี้ยว',      name_mm:'ပၢၵ်ႇၵၢတ်ႈၶဵမ်',      category:'vegetable', supplier:'Makro/ขอนแก่นผักสด',   unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:2,   currentStock:null, image:null},
  {id:'v11',name_th:'กระเทียมจีน',           name_mm:'ၵႃႇတပ်ႉၶႄႇ',          category:'vegetable', supplier:'Makro/ขอนแก่นผักสด',   unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:1,   currentStock:null, image:null},
  {id:'v12',name_th:'กระเทียมดอง แม่จินต์',  name_mm:'ၵႃႇတပ်ႉၶဵမ်',         category:'vegetable', supplier:'Makro',                unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.5, currentStock:null, image:null},
  {id:'v13',name_th:'เห็ดหอม',               name_mm:'ႁဵတ်ႈႁုၼ်ႈ',          category:'vegetable', supplier:'Makro',                unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'v14',name_th:'พริกขี้หนู',             name_mm:'မၢၵ်ႇၽိၵ်ႇၼွႆႉ',     category:'vegetable', supplier:'ขอนแก่นผักสด',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'v15',name_th:'มะระจีน',               name_mm:'မၢၵ်ႇတွမ်ႇ',          category:'vegetable', supplier:'ขอนแก่นผักสด',         unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:1,   currentStock:null, image:null},
  {id:'v16',name_th:'งาขาว',                 name_mm:'မေႃၶၢဝ်',             category:'vegetable', supplier:'Makro',                unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  // สมุนไพรจีน
  {id:'h1', name_th:'เม็ดเฉาก๊วย',          name_mm:'မၢၵ်ႇၶဝ်ႈႁ်ႅ',        category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.3, currentStock:null, image:null},
  {id:'h2', name_th:'กำเช่า ชะเอมเทศ',       name_mm:'ၵမ်ႉဢေႇမ်ႇ',          category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'h3', name_th:'ปักคี้',               name_mm:'ပႅၵ်ႉၶီ',             category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'h4', name_th:'ฮวยซัว',              name_mm:'ႁူဝ်ႇသႃ',             category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'h5', name_th:'เก๋ากี้',              name_mm:'ၵမ်ႉၵ်ီ',             category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'h6', name_th:'ตังกุย',              name_mm:'တႃႇၵုၼ်း',            category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'h7', name_th:'ตังเซียม',             name_mm:'တႃႇသမ်ႈ',             category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  {id:'h8', name_th:'พุทราจีน',             name_mm:'မၢၵ်ႇၶဵဝ်ၶႄႇ',        category:'herb', supplier:'Shopee', unit_th:'กก.', unit_mm:'ၵီႇလူဝ်ႇ', minStock:0.2, currentStock:null, image:null},
  // เครื่องปรุงเพิ่มเติม
  {id:'s26',name_th:'ซอสเหยาะ แม็กกี้',     name_mm:'ၼမ်ႉမႅၵ်ႇၵ်ီ',        category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s27',name_th:'คนอร์ไก่ ซุปก้อน',     name_mm:'ၵိုၵ်းႁူမ်ႈၵႆႇ',       category:'seasoning', supplier:'Makro',    unit_th:'กล่อง',unit_mm:'ၵႃႉ',    minStock:2,  currentStock:null, image:null},
  {id:'s28',name_th:'ซวงเจียแดง',           name_mm:'ဢုမ်ႈၶျမ်ႈ',          category:'seasoning', supplier:'Makro',    unit_th:'ขวด', unit_mm:'ၵမ်း',     minStock:2,  currentStock:null, image:null},
  {id:'s29',name_th:'ชาจีน',               name_mm:'လဵၵ်ႉၶႄႇ',            category:'seasoning', supplier:'Makro',    unit_th:'กล่อง',unit_mm:'ၵႃႉ',    minStock:2,  currentStock:null, image:null},
  {id:'s30',name_th:'น้ำแร่',               name_mm:'ၼမ်ႉမၢႆ',             category:'seasoning', supplier:'Makro',    unit_th:'แพ็ก',unit_mm:'ပႅၵ်ႉ',   minStock:5,  currentStock:null, image:null},
  // บรรจุภัณฑ์ & วัสดุ
  {id:'pk1', name_th:'ถุง 9×8',            name_mm:'ထူင် 9×8',             category:'packaging', supplier:'มหาชัย', unit_th:'ม้วน',unit_mm:'ၶွင်ႇ',    minStock:5,   currentStock:null, image:null},
  {id:'pk2', name_th:'ถุงน้ำราด 5×8',       name_mm:'ထူင်ၼမ်ႉႁူမ်ႈ 5×8',   category:'packaging', supplier:'มหาชัย', unit_th:'ม้วน',unit_mm:'ၶွင်ႇ',    minStock:5,   currentStock:null, image:null},
  {id:'pk3', name_th:'ถุงพริกกระเทียม 3×5', name_mm:'ထူင်မၢၵ်ႇၽိၵ်ႇ 3×5',  category:'packaging', supplier:'มหาชัย', unit_th:'ม้วน',unit_mm:'ၶွင်ႇ',    minStock:3,   currentStock:null, image:null},
  {id:'pk4', name_th:'กล่องใสขาวสีดำ',      name_mm:'ၵႃႉမၢၵ်ႇမိူင်း',       category:'packaging', supplier:'มหาชัย', unit_th:'ใบ',  unit_mm:'ၸႄႈ',     minStock:200, currentStock:null, image:null},
  {id:'pk5', name_th:'กล่องใสขาวสีขาว',     name_mm:'ၵႃႉၶၢဝ်',             category:'packaging', supplier:'มหาชัย', unit_th:'ใบ',  unit_mm:'ၸႄႈ',     minStock:200, currentStock:null, image:null},
  {id:'pk6', name_th:'ถ้วยน้ำจิ้ม',          name_mm:'ႁူဝ်ၼမ်ႉၶဵမ်',        category:'packaging', supplier:'มหาชัย', unit_th:'ใบ',  unit_mm:'ႁူဝ်',    minStock:200, currentStock:null, image:null},
  {id:'pk7', name_th:'ทิชชูวางโต๊ะ',         name_mm:'တိသျုႉ',              category:'packaging', supplier:'มหาชัย', unit_th:'ห่อ', unit_mm:'ႁ်ႅ',     minStock:10,  currentStock:null, image:null},
  {id:'pk8', name_th:'หลอด',                name_mm:'ၸုၵ်ႈ',               category:'packaging', supplier:'มหาชัย', unit_th:'แพ็ก',unit_mm:'ပႅၵ်ႉ',   minStock:5,   currentStock:null, image:null},
  {id:'pk9', name_th:'ยางรัด',              name_mm:'ၵမ်ႉၸၢၵ်ႈ',           category:'packaging', supplier:'มหาชัย', unit_th:'ถุง', unit_mm:'ထူင်',     minStock:2,   currentStock:null, image:null},
  {id:'pk10',name_th:'ถุงมือสีดำ',           name_mm:'မိုဝ်ႉမိူင်း',         category:'packaging', supplier:'มหาชัย', unit_th:'กล่อง',unit_mm:'ၵႃႉ',   minStock:2,   currentStock:null, image:null},
  {id:'pk11',name_th:'ถุงขยะ',              name_mm:'ထူင်ၵၢတ်ႈ',           category:'packaging', supplier:'มหาชัย', unit_th:'ม้วน',unit_mm:'ၶွင်ႇ',    minStock:3,   currentStock:null, image:null},
  {id:'pk12',name_th:'แผ่นแรป',             name_mm:'ၽႅၼ်ႇသႅင်ႈ',          category:'packaging', supplier:'มหาชัย', unit_th:'ม้วน',unit_mm:'ၶွင်ႇ',    minStock:2,   currentStock:null, image:null},
  {id:'pk13',name_th:'เทปใส',               name_mm:'တိပ်ႉၸၢင်ႈ',          category:'packaging', supplier:'มหาชัย', unit_th:'ม้วน',unit_mm:'ၶွင်ႇ',    minStock:3,   currentStock:null, image:null},
  {id:'pk14',name_th:'ลูกแม็ก',             name_mm:'မၢၵ်ႇသိၢင်ႈ',         category:'packaging', supplier:'มหาชัย', unit_th:'กล่อง',unit_mm:'ၵႃႉ',   minStock:2,   currentStock:null, image:null},
  {id:'pk15',name_th:'น้ำยาล้างจาน',         name_mm:'ၼမ်ႉၽုင်ၶႃႈ',         category:'packaging', supplier:'Makro',   unit_th:'ขวด', unit_mm:'ၵမ်း',    minStock:3,   currentStock:null, image:null},
  {id:'pk16',name_th:'น้ำยาถูพื้น',          name_mm:'ၼမ်ႉၽုင်ၵႆ',          category:'packaging', supplier:'Makro',   unit_th:'ขวด', unit_mm:'ၵမ်း',    minStock:2,   currentStock:null, image:null},
  {id:'pk17',name_th:'น้ำยาเช็ดโต๊ะ',        name_mm:'ၼမ်ႉၽုင်တင်ႈ',        category:'packaging', supplier:'Makro',   unit_th:'ขวด', unit_mm:'ၵမ်း',    minStock:2,   currentStock:null, image:null},
]

export const DEFAULT_CATEGORIES: Category[] = [
  {id:'pork',      name_th:'เนื้อหมู',             emoji:'🥩', sort_order:0},
  {id:'chicken',   name_th:'เนื้อไก่',             emoji:'🐔', sort_order:1},
  {id:'ready',     name_th:'ของสำเร็จรูป',         emoji:'🥚', sort_order:2},
  {id:'seasoning', name_th:'เครื่องปรุง',          emoji:'🧂', sort_order:3},
  {id:'vegetable', name_th:'ผัก & สมุนไพร',       emoji:'🥬', sort_order:4},
  {id:'herb',      name_th:'สมุนไพรจีน',           emoji:'🌿', sort_order:5},
  {id:'packaging', name_th:'บรรจุภัณฑ์ & วัสดุ', emoji:'📦', sort_order:6},
]

export const DEFAULT_SUPPLIERS: Supplier[] = [
  {id:'ds1', name:'เบทาโกร'},
  {id:'ds2', name:'เฮียติ่ง'},
  {id:'ds3', name:'มหาชัย'},
  {id:'ds4', name:'Makro'},
  {id:'ds5', name:'ขอนแก่นผักสด'},
  {id:'ds6', name:'Shopee'},
  {id:'ds7', name:'Go Wholesale'},
]
